apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java
spec:
  selector:
    matchLabels:
      app: hello-java
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
      - name: hello-java
        image: localhost:5000/hello-java:latest
        ports:
          - containerPort: 8080
