apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java
spec:
  template:
    spec:
      containers:
      - name: hello-java
        resources:
          limits:
            memory: 512Mi
